---
- hosts: webservers 
  become: True
  tasks:
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
